# Generated by Django 6.0.6 on 2026-07-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
